apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2048
  namespace: pipline
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: m2048
        image: juixtu/2048:v3
        ports:
        - name: java
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: m2048
  namespace: pipline
spec:
  selector:
    app: java
  ports:
  - name: java
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32713
  type: NodePort
